### PR TITLE
extended SCP03Wrapper to use extended length APDUs

### PR DESCRIPTION
**Pull request by tsenger**
**Problem**
SCP03Wrapper throws IllegalArgumentException if using SCP03 with Command APDU in extended length format (LC encoded in 3 bytes instead of 1 byte).  Example:

> java -jar gp.jar --mode enc --mode mac --mode renc --mode rmac --sdaid D276000005123456 -s 80c4000000018bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0001 -d
> 
> GlobalPlatformPro 19.01.22-0-gf94d7f5
> Running on Linux 4.18.0-16-generic amd64, Java 11.0.1 by Oracle Corporation
> # Detected readers from JNA2PCSC
> [*] SCM Microsystems Inc. SCR 331 [CCID Interface] (60400069) 00 00
> SCardConnect("SCM Microsystems Inc. SCR 331 [CCID Interface] (60400069) 00 00", T=*) -> T=1, 3BF99600008031FE4553434537202000202007
> SCardBeginTransaction("SCM Microsystems Inc. SCR 331 [CCID Interface] (60400069) 00 00")
> A>> T=1 (4+0008) 00A40400 08 D276000005123456 00
> A<< (0016+2) (21ms) 556946456E634170706C65745F302E35 9000
> Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
> A>> T=1 (4+0008) 80500000 08 9D33CDBCCF02B1B1 00
> A<< (0032+2) (51ms) 00005112000B002D8717010370A0D3A98C984713B016B5FB3E3A62B04100001C 9000
> A>> T=1 (4+0016) 84823300 10 3A0341920E26B901BFCBB4FBC01CD747
> A<< (0000+2) (19ms) 9000
> SCardEndTransaction(SCM Microsystems Inc. SCR 331 [CCID Interface] (60400069) 00 00)
> SCardDisconnect("SCM Microsystems Inc. SCR 331 [CCID Interface] (60400069) 00 00", true)
> 
> [DEBUG] GlobalPlatform - (I)SD AID: D276000005123456
> [WARN] GlobalPlatform - Could not parse SELECT response: arraycopy: last source index 107 out of bounds for byte[16]
> [TRACE] GlobalPlatform - Generated host challenge: xxxxxxxxxxxxxxxxxxxx
> [DEBUG] GlobalPlatform - Host challenge: xxxxxxxxxxxxxxxxxxxx
> [DEBUG] GlobalPlatform - Card challenge: xxxxxxxxxxxxxxxxxxxx
> [DEBUG] GlobalPlatform - Card reports SCP03 i=70 with key version 1 (0x01)
> [DEBUG] GlobalPlatform - Will do SCP03 (3)
> [DEBUG] PlaintextKeys - Card keys: {ENC=type=RAW bytes=404142434445464748494A4B4C4D4E4F, DEK=type=RAW bytes=404142434445464748494A4B4C4D4E4F, MAC=type=RAW bytes=404142434445464748494A4B4C4D4E4F}
> [TRACE] PlaintextKeys - Session keys: {RMAC=type=AES bytes=574B7B210C879F3FAB5A97336E9A95DC kcv=23C45B, ENC=type=AES bytes=7A2FEBB04502827A5EA47B772F6EA5F3 kcv=607C60, DEK=type=RAW bytes=404142434445464748494A4B4C4D4E4F, MAC=type=AES bytes=0C93CA95209668AEBD3DBE07851E10F5 kcv=802C92}
> [DEBUG] GlobalPlatform - Verified card cryptogram: xxxxxxxxxxxxxxxxxxxx
> [DEBUG] GlobalPlatform - Calculated host cryptogram: xxxxxxxxxxxxxxxxxxxx
> Exception in thread "main" java.lang.IllegalArgumentException: Invalid APDU: length=414, b1=152
> 	at java.smartcardio/javax.smartcardio.CommandAPDU.parse(CommandAPDU.java:318)
> 	at java.smartcardio/javax.smartcardio.CommandAPDU.<init>(CommandAPDU.java:98)
> 	at pro.javacard.gp.SCP03Wrapper.wrap(SCP03Wrapper.java:111)
> 	at pro.javacard.gp.GlobalPlatform.transmit(GlobalPlatform.java:519)
> 	at pro.javacard.gp.GPTool.main(GPTool.java:340)

**Solution**
I modified the SCP03Wrapper, so that it uses the correct encoding for LC byte(s). Example:

> java -jar gp.jar --mode enc --mode mac --mode renc --mode rmac --sdaid D276000005123456 -s 80c4000000018bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0001 -d
> Output: GlobalPlatformPro 19.01.22-0-gf94d7f5-dirty
> Running on Linux 4.18.0-16-generic amd64, Java 11.0.1 by Oracle Corporation
> # Detected readers from JNA2PCSC
> [*] SCM Microsystems Inc. SCR 331 [CCID Interface] (60400069) 00 00
> SCardConnect("SCM Microsystems Inc. SCR 331 [CCID Interface] (60400069) 00 00", T=*) -> T=1, 3BF99600008031FE4553434537202000202007
> SCardBeginTransaction("SCM Microsystems Inc. SCR 331 [CCID Interface] (60400069) 00 00")
> A>> T=1 (4+0008) 00A40400 08 D276000005123456 00
> A<< (0016+2) (22ms) 556946456E634170706C65745F302E35 9000
> Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
> A>> T=1 (4+0008) 80500000 08 CDA7B007FE697F08 00
> A<< (0032+2) (50ms) 00005112000B002D87170103708874CAAEE3E6219CDC35F98279BC29D000001D 9000
> A>> T=1 (4+0016) 84823300 10 4A45C200481B0A3266EAFA7FA16B79CF
> A<< (0000+2) (19ms) 9000
> A>> T=1 (4+0408) 84C40000 000198 5B5B2DC0EA10754FC5068BDB7E18748DA43655A7E035B2612975E3671834E9E006DBE8734F9A35250E52BCE0926790487676CBD7E0EE74EA247ADD75BABEBAF96EBA6896DB9CEA2066817CCC9CE59528035136A446F56943EFDE3AA296E1F0FDF42952C06D3863CB0E860555E1A531854642051753733E5282D7B58C1B6BF3723EFEAD10068AE8B9A9AD7D3E57708BE88CB4AA1FC46A2D32 887BFB28A3F24DD94EE07E53D28BE4BACB11E7D5712F7F9B0C7D3CC811069EA0622539A18E4993F0B1BAD628A3761735C1459843AAEE2F9C1DCAC6FACF1A747E65C3867C04C3F427102DE79240166F8503BF7F7F66F039D7AC6B847AA175B3D9B712B2169CB66F18A6A01B6494B69BAC1CDF696D2087315E4BA56BEB41FD9BD354322AF7AD7B53F5C0244DDB3A645738828A2E21E76ED2B94E87852493B50888C7EACA57317E6991A129F9D2367D0E3ADC1DE83BC6FF5BA134F2D721AAF143DCA933A1A7BD03C0BDF4EB03F71805CD3FEBB4885FD35AF6DE68FC5DCFE5706BB3822405C79ABF6DF315FF67107DD32515D6FF116761290F3FE6F8377E24EBB2100001
> A<< (0008+2) (184ms) 708AE14A2F3B8481 9000
> SCardEndTransaction(SCM Microsystems Inc. SCR 331 [CCID Interface] (60400069) 00 00)
> SCardDisconnect("SCM Microsystems Inc. SCR 331 [CCID Interface] (60400069) 00 00", true)
> 
> Error: [DEBUG] GlobalPlatform - (I)SD AID: D276000005123456
> [WARN] GlobalPlatform - Could not parse SELECT response: arraycopy: last source index 107 out of bounds for byte[16]
> [TRACE] GlobalPlatform - Generated host challenge: xxxxxxxxxxxxxxxxxxxx
> [DEBUG] GlobalPlatform - Host challenge: xxxxxxxxxxxxxxxxxxxx
> [DEBUG] GlobalPlatform - Card challenge: xxxxxxxxxxxxxxxxxxxx
> [DEBUG] GlobalPlatform - Card reports SCP03 i=70 with key version 1 (0x01)
> [DEBUG] GlobalPlatform - Will do SCP03 (3)
> [DEBUG] PlaintextKeys - Card keys: {ENC=type=RAW bytes=404142434445464748494A4B4C4D4E4F, DEK=type=RAW bytes=404142434445464748494A4B4C4D4E4F, MAC=type=RAW bytes=404142434445464748494A4B4C4D4E4F}
> [TRACE] PlaintextKeys - Session keys: {RMAC=type=AES bytes=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx kcv=03572C, ENC=type=AES bytes=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx kcv=C3177C, DEK=type=RAW bytes=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, MAC=type=AES bytes=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx kcv=5172C8}
> [DEBUG] GlobalPlatform - Verified card cryptogram: xxxxxxxxxxxxxxxxxxxx
> [DEBUG] GlobalPlatform - Calculated host cryptogram: xxxxxxxxxxxxxxxxxxxx

### CODE REVIEW

**Comment by martinpaljak** [comment]
For some reason I recall GP defining only short format APDU-s explicitly, am I wrong?

**Comment by martinpaljak** [comment]
> All GlobalPlatform APDU command messages (excluding the APDU header) are limited to 255 bytes in length. All GlobalPlatform APDU commands that expect response data have their Le byte set to zero, indicating that all available response data shall be returned. According to [ISO 7816-4], all GlobalPlatform responses returned in APDU response messages shall have a maximum length of 256 bytes of response data.

**Comment by martinpaljak** [comment]
11.1.5 APDU Message and Data Length (v2.3.1)

**Comment by tsenger** [comment]
I think it could it interpreted that only GlobalPlatform APDU command messages as EXTERNAL AUTHENTICATE, INTERNAL AUTHENTICATE, eg. are limited to to 255 bytes.
Here my own Javacard applet ( AID: D276000005123456) uses the GP secure messaging for its own commands, which are not limited to 255 data bytes, but could also use extended length APDUs.
The applet is running on a G+D Sm@rtCafe Expert 7.0 C3 card. So it seems that at least G+D interpreted the specs as mentioned above.
Another point is: Why should the GlobalPlatform.Pro tools refuse extended length APDU on its own? If the card doesn't allow extended length APDU it will refuse them anyway.

**Comment by martinpaljak** [comment]
Absolutely. Just trying to make sure that "anomalies" or difficult locations get comments in source code for future generations (or me myself in 3 weeks)

**Comment by tsenger** [comment]
Yeah, good point. ;-)

**Pull request merged**
