### PR TITLE
Adding options to lock card with three differnet keys (ENC, MAC, DEK).

### PR DESCRIPTION
**Pull request by gmkbenjamin**
Adding options to lock card with three differnet keys (ENC, MAC, DEK). And fixed a use of a private method from a different class.

### CODE REVIEW

**Comment by martinpaljak** [comment]
Thanks!

I will dwell on this for a day or two.

What about having a "-lock-<diversificationmethod>" instead? that would indicate that the master key specified with `-lock` should be diversified for the given card with the given method? The whole -lock/unlock thing is meant for easy and naive approach to card key management. I do not yet have a good idea how to expose this without making the cli option set long and cumbersome (which is not bad per se, but instead of becoming the next OpenSSL I would like to keep it "sane" and a bit opinionated by default).

**Comment by gmkbenjamin** [comment]
Understand your hesitation. The only reason I added this was because there's real use case in one of the projects that I'm working on. The card vendor provided 3 static keys, we messed up some cards during during testing and we had to revert the keys back to factory keys.

**Comment by martinpaljak** [comment]
Could you please split the array issue into a separate commit or squash the last two ones?

**Comment by martinpaljak** [comment]
Or I will fix the oneliner bug without a PR and will still think about the CLI options ?

**Comment by gmkbenjamin** [comment]
Sorry I'm a noob. Feel free to fix the bug.

**Comment by martinpaljak** [comment]
The array size fix is in the master.

**Pull request closed without merging**
