### PR TITLE
Incorrect length in install for install 

### LINKED ISSUE #241: Incorrect length in install for install
I was trying that installAndMakeSelectable command and seems that the length of install params is not correctly encoded, per spec (GPC_CardSpecification_v2.3.1_PublicRelease_CC) should be encoded as normal tlv without tag so:

- 0 - 127: 0-7F
- 127-255: 81 XX
- 255 - 65535: 82 XX XX

https://github.com/martinpaljak/GlobalPlatformPro/blob/847f91f7a3aab5d7e0c5fe9b7f5b620fa55119ae/library/src/main/java/pro/javacard/gp/GPSession.java#L659

Instead of:

bo.write(installParams.length);

Shoulde be:

bo.write(GPUtils.encodeLength(installParams.length));

By this logic loadCap might have the same issue but I didnt check either the specs nor tested the command.

One more thing, I realized that while version keeps bumping, its not getting pushed to maven central, is this okay?

Regards

### PR DESCRIPTION
**Pull request by xavo95**
Fix #241

### CODE REVIEW

**Comment by martinpaljak** [comment]
Things to consider:
- metadata from the card is often incorrect (or some vendor-specific NDA document tells the actual implementation is limited compared to the spec); the best to do is to use it as a hint to provide better defaults, but in a failsafe way.
- explicit user input should be respected over implicit assumptions: if giving input of 400 bytes, length should be encoded as necessary (in 2.3 style) and command sent no matter what (because previous point). But a helpful warning might be relevant. In GPTool, not in the library part.

So encoding all lengths "properly" as default is OK. Just need to check the specs if there are fancy corner cases, because GPC 2.2.1 11.1.5 tells:
> All length fields of GlobalPlatform messages and data objects defined in this specification, except for Lc
> and Le, are coded as defined for ASN.1 BER-TLV (see ISO 8825-1): 1 byte for a length up to 127, 2
> bytes for a length up to 255, and 3 bytes for a length up to 65535, **except where otherwise stated**.

and there were corner cases for one byte encoding with keys at least.

**Comment by martinpaljak** [comment]
eg gpc 2.2.1 11.5.2.3.1 
> "The length field for a Load Token is as defined for ASN.1 BER-TLV (see ISO 8825-1) except that the length 128 may also be coded on one byte as '80'."

**Comment by xavo95** [comment]
Okay I cant today but I will try to look at it too during this week, if its okay with you

**Comment by martinpaljak** [comment]
Sure, a PR is welcome, but I'd anyway fix it when working on GP at some point, thus keeipng it open.

**Comment by martinpaljak** [comment]
The issue is fixed by #246 whereas the UX to warn nicely will happen at a later time.

**Pull request closed without merging**
